services:
  super-invoicer:
    build: .
    command:
      - --basic-auth.enable
      - --basic-auth.username=foo
      - --basic-auth.password=bar
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
