services:
  super-invoicer:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: mysql # must not defined like this in production env.
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
